start_page: "https://24ka.com.ua/ua/g134495122-bolgarki"
selectors:
    product_link_selector: "//a[@class='cs-goods-title']"
    name_selector: "//h1//span['text']"
    price_selector: "//p[@class='b-product-cost__price']"
    description_selector: "//div[@class='b-user-content']//p//span"
    image_selector: ".cs-pictures__img"
    category: "24ka"

methods:
    run_save_to_csv
    run_save_to_json
    run_save_to_yaml
    run_save_to_sqlite
    run_save_to_mongodb